[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# 3-layer drawing for Gateway
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.config.center.soul_pos and (self.config.center.discovered or self.bypass_discovery_center) then"
position = "before"
payload = '''
if self.ability.name == 'Gateway' and (self.config.center.discovered or self.bypass_discovery_center) then
    local scale_mod2 = 0.07-- + 0.02*math.cos(1.8*G.TIMERS.REAL) + 0.00*math.cos((G.TIMERS.REAL - math.floor(G.TIMERS.REAL))*math.pi*14)*(1 - (G.TIMERS.REAL - math.floor(G.TIMERS.REAL)))^3
    local rotate_mod2 = 0--0.05*math.cos(1.219*G.TIMERS.REAL) + 0.00*math.cos((G.TIMERS.REAL)*math.pi*5)*(1 - (G.TIMERS.REAL - math.floor(G.TIMERS.REAL)))^2
    self.children.floating_sprite2:draw_shader('dissolve',0, nil, nil, self.children.center,scale_mod2, rotate_mod2,nil, 0.1--[[ + 0.03*math.cos(1.8*G.TIMERS.REAL)--]],nil, 0.6)
    self.children.floating_sprite2:draw_shader('dissolve', nil, nil, nil, self.children.center, scale_mod2, rotate_mod2) 
    
    local scale_mod = 0.05 + 0.05*math.sin(1.8*G.TIMERS.REAL) + 0.07*math.sin((G.TIMERS.REAL - math.floor(G.TIMERS.REAL))*math.pi*14)*(1 - (G.TIMERS.REAL - math.floor(G.TIMERS.REAL)))^3
    local rotate_mod = 0.1*math.sin(1.219*G.TIMERS.REAL) + 0.07*math.sin((G.TIMERS.REAL)*math.pi*5)*(1 - (G.TIMERS.REAL - math.floor(G.TIMERS.REAL)))^2

    self.children.floating_sprite.role.draw_major = self
    self.children.floating_sprite:draw_shader('dissolve',0, nil, nil, self.children.center,scale_mod, rotate_mod,nil, 0.1 + 0.03*math.sin(1.8*G.TIMERS.REAL),nil, 0.6)
    self.children.floating_sprite:draw_shader('dissolve', nil, nil, nil, self.children.center, scale_mod, rotate_mod)
    
end
'''
match_indent = true
overwrite = false

# Gateway spawn logic
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if not forced_key and soulable and (not G.GAME.banned_keys['c_soul']) then"
position = "after"
payload = '''
if (_type == 'Spectral') and
not (G.GAME.used_jokers['c_cry_gateway'] and not next(find_joker("Showman")))  then 
    if pseudorandom('cry_gateway_'.._type..G.GAME.round_resets.ante) > 0.997 then
        forced_key = 'c_cry_gateway'
    end
end
'''
match_indent = true
overwrite = false

# Exotic spawn logic
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "rarity = (_legendary and 4) or (rarity > 0.95 and 3) or (rarity > 0.7 and 2) or 1"
position = "at"
payload = "rarity = (type(rarity) == 'string' and rarity) or (_legendary and 4) or (rarity > 0.95 and 3) or (rarity > 0.7 and 2) or 1"
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if v.name == 'Black Hole' or v.name == 'The Soul' then"
position = "at"
payload = "if v.name == 'Black Hole' or v.name == 'The Soul' or v.name == 'Gateway' then"
match_indent = true
overwrite = true