[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Joker Sell List
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = 'self:calculate_joker{selling_self = true}'
position = "before"
payload = '''
if self.config.center.set == 'Joker' then
	if G.GAME.jokers_sold then
		local contained = false
		for i = 1, #G.GAME.jokers_sold do
			if self.config.center.key == G.GAME.jokers_sold[i] then contained = true end
		end
		if not contained then table.insert(G.GAME.jokers_sold, self.config.center.key) end
	else
		G.GAME.jokers_sold = {self.config.center.key}
	end
end
'''
match_indent = true