[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# The Tax effect
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "func = (function()  update_hand_text({delay = 0, immediate = true}, {mult = 0, chips = 0, chip_total = math.floor(hand_chips*mult), level = '', handname = ''});play_sound('button', 0.9, 0.6);return true end)"
position = "at"
payload = "func = (function()  update_hand_text({delay = 0, immediate = true}, {mult = 0, chips = 0, chip_total = not G.GAME.blind.disabled and G.GAME.blind.name == 'cry-Tax' and math.floor(math.min(0.4*G.GAME.blind.chips,hand_chips*mult)+0.5) or math.floor(hand_chips*mult), level = '', handname = ''});play_sound('button', 0.9, 0.6);return true end)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "ease_to = G.GAME.chips + math.floor(hand_chips*mult),"
position = "at"
payload = "ease_to = G.GAME.chips + (not G.GAME.blind.disabled and G.GAME.blind.name == 'cry-Tax' and math.floor(math.min(0.4*G.GAME.blind.chips,hand_chips*mult)+0.5) or math.floor(hand_chips*mult)),"
match_indent = true