[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Remove voucher at start of run
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.GAME.current_round.voucher = G.SETTINGS.tutorial_progress and G.SETTINGS.tutorial_progress.forced_voucher or get_next_voucher_key()"
position = "at"
payload = '''
if not self.GAME.modifiers.no_vouchers then
    self.GAME.current_round.voucher = G.SETTINGS.tutorial_progress and G.SETTINGS.tutorial_progress.forced_voucher or get_next_voucher_key()
else
    very_fair_quip = pseudorandom_element(very_fair_quips, pseudoseed("cry_very_fair"))
end
'''
match_indent = true
overwrite = true

# Remove voucher when defeating boss
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.current_round.voucher = get_next_voucher_key()"
position = "at"
payload = '''
if not G.GAME.modifiers.no_vouchers then
    G.GAME.current_round.voucher = get_next_voucher_key()
else
    very_fair_quip = pseudorandom_element(very_fair_quips, pseudoseed("cry_very_fair"))
end
'''
match_indent = true
overwrite = true

# Change empty voucher text on Very Fair Deck
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "{n=G.UIT.T, config={text = 'DEFEAT', scale = 0.6, colour = G.C.WHITE}}"
position = "at"
payload = "{n=G.UIT.T, config={text = G.GAME.modifiers.no_vouchers and very_fair_quip[1] or 'DEFEAT', scale = 0.6, colour = G.C.WHITE}}"
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "{n=G.UIT.T, config={text = 'BOSS BLIND', scale = 0.4, colour = G.C.WHITE}}"
position = "at"
payload = "{n=G.UIT.T, config={text = G.GAME.modifiers.no_vouchers and very_fair_quip[2] or 'BOSS BLIND', scale = 0.4, colour = G.C.WHITE}}"
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "{n=G.UIT.T, config={text = 'TO RESTOCK', scale = 0.4, colour = G.C.WHITE}}"
position = "at"
payload = "{n=G.UIT.T, config={text = G.GAME.modifiers.no_vouchers and very_fair_quip[3] or 'TO RESTOCK', scale = 0.4, colour = G.C.WHITE}}"
match_indent = true
overwrite = true

